spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dino21824@gmail.com
    password: csnocnmllpvfxqsh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver


server:
  port: 8090
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook